name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  DB_NAME: test_db
  DB_USER: root
  DB_PASSWORD: root
  DB_HOST: localhost

jobs:

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql ${{ env.DB_NAME }} -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < backend/dbseed/db.sql
      - run: yarn --frozen-lockfile --cwd backend
      - run: yarn --frozen-lockfile --cwd frontend

      - name: Backend ESLint
        run: yarn eslint --prefix backend
      - name: Backend Unit Tests
        run: yarn test:unit --prefix backend
      - name: Backend Integration Tests
        run: yarn test:integration --prefix backend
      - name: Backend Installing Dependencies
        run: npm ci --prefix backend
      - name: Backend Deployment
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./backend/*
          remote_path: /var/www/birdie-back/
          remote_host: ec2-18-157-239-238.eu-central-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.BIRDIE_SERVER_SSH_KEY }}"

      - name: Frontend ESLint
        run: yarn lint --prefix frontend
      - name: Frontend Unit Tests
        run: yarn test --prefix frontend
      - name: Frontend Installing Dependencies
        run: npm ci --prefix frontend
      - name: Frontend Build
        run: yarn build --prefix frontend
      - name: Frontend Deployment
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./frontend/build/*
          remote_path: /var/www/birdie-front/
          remote_host: ec2-18-157-239-238.eu-central-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.BIRDIE_SERVER_SSH_KEY }}"