name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  DB_NAME: test_db
  DB_USER: root
  DB_PASSWORD: root
  DB_HOST: localhost

jobs:

  Backend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: 'backend/node_modules'
          key: ${{ runner.os }}-backend-node-${{ hashFiles('backend/yarn-lock.json') }}

      - name: Backend Fetching dependencies
        run: cd backend && yarn --frozen-lockfile

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql ${{ env.DB_NAME }} -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < backend/dbseed/db.sql

      - name: Backend ESLint
        run: cd backend && yarn lint
      - name: Backend Unit Tests
        run: cd backend && yarn test:unit
      - name: Backend Integration Tests
        run: cd backend && yarn test:integration
      - name: Backend Deployment
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./backend/*
          remote_path: /var/www/birdie-back/
          remote_host: ec2-18-157-239-238.eu-central-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.BIRDIE_SERVER_SSH_KEY }}"

Frontend:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: 'frontend/node_modules'
          key: ${{ runner.os }}-frontend-node-${{ hashFiles('frontend/yarn-lock.json') }}

      - name: Frontend Fetching dependencies
        run: cd frontend && yarn --frozen-lockfile

      - name: Frontend ESLint
        run: cd frontend && yarn lint
      - name: Frontend Unit Tests
        run: cd frontend && yarn test
      - name: Frontend Build
        run: cd frontend && yarn build
      - name: Frontend Deployment
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./frontend/build/*
          remote_path: /var/www/birdie-front/
          remote_host: ec2-18-157-239-238.eu-central-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.BIRDIE_SERVER_SSH_KEY }}"